# This is a basic workflow to help you get started with Actions

name: Update the GitHub Profile README

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "0 */4 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Update the GitHub Profile README
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: theboi/github-update-readme@v1.3.0

      # Runs a single command using the runners shell
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "NOW BUILDING..."
          subhead: "Here's a sneak preview of what I am currently working on."
          footer:  "Hi!👋🏽  My name is Haja and I am an enthusiastic mobile and web developer. As a product-driven software engineer who loves collaborating with other talented and enthusiastic people, I love learning new technologies, building great software, and solving real-world problems with code.\  A sneak preview of my in-progress projects will be shown above. **This feed is auto-updated based on my activity and configurations, using Github Actions, by @theboi.  Feel free to reach out and say hello!

                  I've worked with...\
                   *Java (Android), Python, Flask, Django, Javascript, React Js, GraphQL, MongoDB, Postgres, HTML5, CSS3, SCSS, Material UI, Styled Components, Enzyme, Jest, AWS( EC2, S3, Elastic Beanstalk) ...but I will learn anything that is needed for the project* ✨✨✨ 


                  😄 My Pronouns: She/her\

                  📫 How to reach me: ...\
                     - [Linked In](https://www.linkedin.com/in/haja-childs-dev-md/)
                     - [Twitter](https://twitter.com/tech_natural)

                  💻 I’m currently working on ...\
                    - A web app with Python Flask, Ariadne (GraphQL), Docker and React Js  

                  🌱 I’m currently learning ...\
                    - Typescript
                    - Ariadne

                  ⚡ My favorite binge-watched shows right now ...
                     - Stranger Things, Severance, The Expanse, Umbrella Academy"\

          repoCount: "1"
          reposPerRow: "1"
          imageSize:  "width:900 height:500"
          excludeActivity: '["WatchEvent"]'
          excludeRepo: '["HajaSChilds/HajaSChilds", "HajaSChilds/100-days-of-code"]'     
          
